<Project Sdk="Microsoft.NET.Sdk">
  <Sdk Name="Aspire.AppHost.Sdk" Version="9.2.0" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>f33c5ecd-10d7-47d0-bcea-414d8aefb620</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="9.4.1" />
    <PackageReference Include="Aspire.Hosting.Azure.CognitiveServices" Version="9.4.1" />
    <PackageReference Include="Aspire.Hosting.Keycloak" Version="9.4.1-preview.1.25408.4" />
    <PackageReference Include="Aspire.Hosting.NodeJs" Version="9.4.1" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="9.4.1" />
    <PackageReference Include="Aspire.Hosting.RabbitMQ" Version="9.4.1" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="9.4.1" />
    <PackageReference Include="Aspire.Hosting.SqlServer" Version="9.4.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Gateway\Gateway.csproj" />
    <ProjectReference Include="..\GH.Admin\GH.Admin\GH.Admin.csproj" />
    <ProjectReference Include="..\GH.Plan.API\GH.Plan.API.csproj" />
    <ProjectReference Include="..\GH.Plan.DbManager\GH.Plan.DbManager.csproj" />
    <ProjectReference Include="..\Todo.API\Todo.API.csproj" />
  </ItemGroup>

</Project>
